### ISSUE TITLE
Kubernetes的组件以及交互过程

### ISSUE THREAD

**Issue by QingyaFan** [QingyaFan/blog#46]
# Kubernetes的核心组件

<img width="641" alt="image" src="https://github.com/QingyaFan/blog/assets/10420579/ce33e640-9209-4346-8a06-53f6a9cf9cde">

- kube-apiserver, 集群管理都经过 apiserver，集群的状态都经由 apiserver 存储到 etcd 中
- kube-controller-manager, 管理k8s自带的控制器，创建对应 pod来达成 controller 的预期状态，例如启动并维护 DaemonSet的控制器Pod，CRD 的 controller 不是由 kube-controller-manager 管理的，当然，crd 的 controller 也需要 manager，一般是通过 `sigs.k8s.io/controller-runtime` 创建一个（NewManager）
- kube-scheduler，分配pod到node的控制面组件，它会根据`约束(constraints)` 和 `可用资源(available resources)` 来给待调度 pod 找一个合适的 node，这里 `约束(constraints)` 和 `可用资源(available resources)` 都是其复杂性的体现。kube-scheduler 是一个参考实现，我们可以实现自己的 scheduler 来代替，且可以有多个scheduler 
- kube-proxy，运行在每个 node 上，实现上使用了 iptables 规则或者 IPVS（IP Virtual Server），在服务之间的通信方面发挥关键作用，提供路由、负载均衡和服务发现功能。这里的负载均衡是指同一应用的多个副本分布在一个node上时，kube-proxy会做这些副本间的负载均衡
- kubelet，运行在node上的代理，启动后会向 apiserver 注册自己，这样 apiserver 就知道集群中有多少 node 了。kubelet的主要职责是确保node 上的容器健康运行，需要运行哪些容器？apiserver 提供，或者 文件、HTTP endpoint。

# 一个yaml apply后到新建成功的过程

我们用一个 postgres的 deployment 来举例：

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16.2-bullseye
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: cheerfun
```

1. kube-apiserver 收到 kubectl 的请求，将 yaml 中定义的期望状态更新到集群中，也就是 etcd中，集群的状态都在这里维护。具体来说，apiserver会解析 yaml 内容，将解析后的信息写入 etcd 中的相应路径，如 deployment、pod、container 都会写入
2. kube-scheduler 常态通过informer 监听集群中的状态变化事件，主要监听的是 node 和 pod 对象。当然，如果有一些复杂的调度逻辑参考了其他对象的状态，也可能会监听其他的对象。这里它监听到 pod 需要新建，通过调度算法确定要调度到的 node，在1.7之前，会创建一个 [Binding](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/types.go#L5275) 对象，kubelet 监听这个对象来执行创建 pod 的操作；在 1.7 之后，binding 成了 pod的一个属性
3. kubelet，kubelet 负责启动调度到所在node 的 pod

```
func startKubelet(k kubelet.Bootstrap, podCfg *config.PodConfig, kubeCfg *kubeletconfiginternal.KubeletConfiguration, kubeDeps *kubelet.Dependencies, enableServer bool) {
	// start the kubelet
	go k.Run(podCfg.Updates())

	// start the kubelet server
	if enableServer {
		go k.ListenAndServe(kubeCfg, kubeDeps.TLSOptions, kubeDeps.Auth, kubeDeps.TracerProvider)
	}
	if kubeCfg.ReadOnlyPort > 0 {
		go k.ListenAndServeReadOnly(netutils.ParseIPSloppy(kubeCfg.Address), uint(kubeCfg.ReadOnlyPort), kubeDeps.TracerProvider)
	}
	go k.ListenAndServePodResources()
}
```

4. 容器引擎，kubelet 会通过 CRI 调用容器引擎来创建容器

总体的流程如下图：

<img width="872" alt="image" src="https://github.com/QingyaFan/blog/assets/10420579/92cf86a4-f6b8-4ad1-b36a-cea7ecc77499">
