### ISSUE TITLE
CRD Controller多副本选主

### ISSUE THREAD

**Issue by QingyaFan** [QingyaFan/blog#55]
CRD Controller部署到集群中，承担着重要的职责，crash会直接导致业务直接停转，高可用非常必要，kubebuilder 创建的 Controller 逻辑中使用了 controller-runtime 包中的 Manager，其中封装了选主逻辑：

```
mgr, err := ctrl.NewManager(ctrl.GetConfigOrDie(), ctrl.Options{
    ...
    LeaderElection:         enableLeaderElection,
    LeaderElectionID:     "81e40fc6.my.domain",
})
```

controller-runtime 的选主逻辑依赖了 client-go，接下来我们来分析一下 client-go 中的选主算法。

# 选主算法

## 选主原理

kube-apiserver 创建/更新 LeaseLock、ConfigMap、Endpoints 保证原子性，谁创建或更新成功谁就成为下一个 Lease 的主。apiserver能保证原子操作的关键是：etcd 提供了强一致性，保障了操作的原子性。

1. 创建锁，可以使用 LeaseLock、ConfigMap 或 Endpoints 作为锁，锁在 namespace 内唯一

```go
lock := resourcelock.LeaseLock{
	LeaseMeta: v1.ObjectMeta{
		Name:      lockName,
		Namespace: lockNamespace,
	},
}
```

LeaseLock 是 kubernetes 1.14 引入，专门用来选主，包含的字段有：

> pkg/apis/coordination/types.go

```
// LeaseSpec is a specification of a Lease.
type LeaseSpec struct {
	// holderIdentity contains the identity of the holder of a current lease.
	// +optional
	HolderIdentity *string
	// leaseDurationSeconds is a duration that candidates for a lease need
	// to wait to force acquire it. This is measure against time of last
	// observed renewTime.
	// +optional
	LeaseDurationSeconds *int32
	// acquireTime is a time when the current lease was acquired.
	// +optional
	AcquireTime *metav1.MicroTime
	// renewTime is a time when the current holder of a lease has last
	// updated the lease.
	// +optional
	RenewTime *metav1.MicroTime
	// leaseTransitions is the number of transitions of a lease between
	// holders.
	// +optional
	LeaseTransitions *int32
}
```

2. 各个副本实例通过创建或更新锁来抢主（leader），抢主成功会执行指定的回调函数

```go
leaderelection.RunOrDie(context.TODO(), leaderelection.LeaderElectionConfig{
	Lock:                    &lock,
	LeaseDuration:   30 * time.Second,
	RenewDeadline: 15 * time.Second,
        RetryPeriod:   2 * time.Second,
	Callbacks: leaderelection.LeaderCallbacks{
		OnNewLeader: func(identity string) {},
	},
})
```

- LeaseDuration 指定选上leader的租约时长，在这个时间内，leader认为自己是合法的，执行相关的操作。如果想要续约，就需要在 LeaseDuration 结束前
- RenewDeadline，leader尝试续约的期限，RenewDeadline的起始时刻和 LeaseDuration 一样。如果 RenewDeadline内没续约，leader 认为自己失去了身份，应该停止当前操作，必要时做好下一个 leader 重拾当前操作的准备。如果 RenewDeadline 内没有续约，其它节点可以在 RenewDeadline 后，LeaseDuration 内进行抢主

LeaseDuration 和 RenewDeadline 的关系是：

```
T0                                T0+15s                             T0+30s
|---------------------------------|----------------------------------|
|        RenewDeadline            |            LeaseDuration         |
```

## etcd 如何保证操作原子性

Etcd 提供强一致性的存储，确保在分布式环境中数据的高可用性和一致性，etcd 通过分布式一致性算法（Raft 协议）确保数据操作的原子性和一致性；etcd 的一致性特性确保了即使在网络分区或节点故障的情况下，数据的操作依然是可预测和可靠的，这对选主机制的正确性至关重要。

# 基于 client-go 的选主示例

我们一般使用 default namespace 来部署应用，默认情况下，default namespace下的 default 账户没有权限访问或控制 Lease 资源，所以我们先创建 ClusterRole 和 RoleBinding 来授予适当的 RBAC 权限：

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lease-manager
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "create", "update", "delete"]

----

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lease-manager-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: lease-manager
  apiGroup: rbac.authorization.k8s.io
```

编写选主测试程序：

```go
func buildClient() (*kubernetes.Clientset, error) {
	cfg, err := rest.InClusterConfig()
	if err != nil {
		return nil, err
	}
	return kubernetes.NewForConfigOrDie(cfg), nil
}

func election(lockName, lockNamespace string) {
	client, err := buildClient()
	if err != nil {
		klog.Fatalf("build client failed, err: %v", err)
	}

	lock := resourcelock.LeaseLock{
		LeaseMeta: v1.ObjectMeta{
			Name:      lockName,
			Namespace: lockNamespace,
		},
		Client: client.CoordinationV1(),
		LockConfig: resourcelock.ResourceLockConfig{
			Identity: PodName,
		},
	}
	leaderelection.RunOrDie(context.TODO(), leaderelection.LeaderElectionConfig{
		Lock:          &lock,
		LeaseDuration: 10 * time.Second,
		RenewDeadline: 5 * time.Second,
		RetryPeriod:   2 * time.Second,
		Callbacks: leaderelection.LeaderCallbacks{
			OnNewLeader: func(identity string) {
				klog.Infof("succeed get leader, id: %s, pod_name: %s", identity, PodName)
			},
			OnStartedLeading: func(ctx context.Context) {
				klog.Infof("started leading, pod_name: %s", PodName)
			},
			OnStoppedLeading: func() {
				klog.Infof("stopped leading, pod_name: %s", PodName)
			},
		},
	})
}
```

```go
package main

import "os"

const PodNameEnvInContainer string = "HOSTNAME"

var PodName string

func init() {
	PodName = os.Getenv(PodNameEnvInContainer)
}

func main() {
	election("test-leader-elect", "default")
}
```

这里我们在容器内通过 HOSTNAME 环境变量获取了 pod name，这个环境变量是 k8s 注入的，当然，在容器内获取pod 信息不止 env 一种，还有 downward api 和 请求 apiserver，downward api 是将一部分信息以文件的形式挂载进了容器，容器通过读文件可以读取这部分信息，kubelet会在每个循环内更新这些信息；相对于 apiserver，信息可能会稍有滞后。请求 apiserver 获取到的信息最为丰富，也最为及时，但太多的请求会导致apiserver 过载。实际业务场景下，根据情况使用即可。

将程序打包成容器，通过一个 3 副本的 deployment 部署到集群中，

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-election
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mock-election
  template:
    metadata:
      labels:
        app: mock-election
    spec:
      containers:
      - name: mock-election
        image: election-mocker:v0.0.1
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
```

要注意，如果你使用的kind作为本地测试环境，要将镜像load进集群：`kind load docker-image election-mocker:v0.0.1`，这样deployment拉取镜像时才不会找不到。

<img width="1129" alt="image" src="https://github.com/QingyaFan/blog/assets/10420579/29e65dda-e351-4d13-8fce-47087030663b">

我们查看各个pod的日志：

<img width="1133" alt="image" src="https://github.com/QingyaFan/blog/assets/10420579/d3bb6fee-f039-43e3-ad45-f9d315a1336f">

可以看到 pod name 是 mock-election-7b6d569d4-kn2jg 的 pod 抢到了主。

这个时候我们delete 掉它，看其它的 pod 是否会抢到主： `kubectl delete pod/mock-election-7b6d569d4-kn2jg`

<img width="1118" alt="image" src="https://github.com/QingyaFan/blog/assets/10420579/1ef5e6af-bad5-4982-844e-d8d022f24e20">

<img width="818" alt="image" src="https://github.com/QingyaFan/blog/assets/10420579/bc95b28d-2365-4e22-9164-bc54e12425c5">

<img width="1128" alt="image" src="https://github.com/QingyaFan/blog/assets/10420579/e0125c4f-0be0-4513-af42-069c8a48cfd6">

我们可以看到主被 mock-election-7b6d569d4-kbfjt 抢到了
