### ISSUE TITLE
scheduling-framework 原理和使用

### ISSUE THREAD

**Issue by QingyaFan** [QingyaFan/blog#56]
# 调度的过程

![image](https://github.com/QingyaFan/blog/assets/10420579/644efc0f-d8d5-46f8-9d92-2f09d60fd3f7)

1. 监听和队列管理：调度器监听（List-Watch）apiserver 感知未绑定的Pod，放入调度队列
2. 过滤：根据一系列预定义的规则对所有节点进行过滤，排除不适合的节点，预定义的规则包括：
    - 污点和容忍度：检查Pod 能否容忍 node 污点（Taints）
    - 节点选择器：检查Pod 的 NodeSelector，确保节点标签（Labels）匹配
    - 亲和与反亲和性：节点亲和性与反亲和性，Pod 间亲和性与反亲和性
    - 节点条件和准备情况：确保 Node 是 Ready 状态，不在网络分区或其它不可用状态
    - 资源过滤：检查节点是否有足够的 CPU、内存和其他资源来满足 Pod 的资源请求和限制
3. 评分（优选）：对过滤剩余的节点运用一系列规则打分，得分越高越适合调度。根据评分结果，选择得分最高的节点。如果有多个节点得分相同，则随机选择一个节点。
    - 资源利用率：倾向于将 Pod 调度到资源利用率较低的节点
    - 数据本地性：倾向于将 Pod 调度到数据本地性好的节点，以减少网络延迟和带宽使用
    - 网络延迟：根据网络拓扑和 Pod 的网络要求对节点进行评分
    - 用户自定义的调度策略：可以自定义调度策略，使用插件或配置文件来定义具体的打分规则
4. 绑定：生成 Bind 对象，将Pod与Node绑定
5. 额外处理：如果以上任何一个环节失败，Pod会被重新添加到调度队列

如果我们想改变调度器的默认行为，有几种方案：
1. 调度器策略配置：通过配置文件自定义调度策略
2. 调度器插件：scheduing-framework [^2] 给在调度过程中一些关键节点开放了扩展点，可以编写自定义调度器插件来实现特定的调度逻辑
3. 多调度器：在同一个集群中运行多个调度器，每个调度器负责不同的调度逻辑或 Pod

## 监听和队列

scheduler 是一个独立的进程，通过 list-watch 的方式监听 Pod 对象，调度器的初始化、调度队列的管理和调度算法的实现在 kubernetes 源码中：

> pkg/scheduler/scheduler.go [^4]

```
// Scheduler watches for new unscheduled pods. It attempts to find
// nodes that they fit on and writes bindings back to the api server.
type Scheduler struct {
        SchedulingQueue internalqueue.SchedulingQueue
        NextPod func(logger klog.Logger) (*framework.QueuedPodInfo, error)
	SchedulePod func(ctx context.Context, fwk framework.Framework, state *framework.CycleState, pod *v1.Pod) (ScheduleResult, error)
}
```

SchedulingQueue：待调度 Pod 任务队列 [^3]，存储等待调度的 Pod
NextPod：从队列中获取下一个待调度Pod，它是一个允许自定义的函数，注释中解释说不使用channel的原因是调度Pod的行为`take some amount of time and we don't want pods to get stale while they sit in a channel`，在New 构造函数中，是这样的实现：`sched.NextPod = podQueue.Pop`

这个队列是一个优先队列，队列头部是最高优先级的 Pending Pod，它包含两个子队列和一个额外数据结构：

- activeQ：存储准备调度的 pods
- backoffQ：存储从 unschedulablePods 中来，可能移入 activeQ 的 pods
- unschedulablePods，已经进行过调度尝试但被标记为 unschedulable 的pods

Pop 方法从队列头获取一个 pod，从 activeQ 取，如果队列是空的，Pop方法是阻塞的，直到有新的 pod 添加进队列，这也是 NextPod 是阻塞操作的源头：

> pkg/scheduler/internal/queue/scheduling_queue.go

```
func NewPriorityQueue(
	lessFn framework.LessFunc,
	informerFactory informers.SharedInformerFactory,
	opts ...Option,
) *PriorityQueue {...
```

> pkg/scheduler/internal/queue/scheduling_queue.go  [^6]

```
type PriorityQueue struct {
        activeQ *heap.Heap
        podBackoffQ *heap.Heap
        unschedulablePods *UnschedulablePods
}
```

SchedulePod：执行具体调度工作，todo

## 打分

以机器资源可用量打分：

> pkg/trimaran/loadvariationriskbalancing/loadvariationriskbalancing.go [^7]

```
// Score : evaluate score for a node
func (pl *LoadVariationRiskBalancing) Score(ctx context.Context, cycleState *framework.CycleState, pod *v1.Pod, nodeName string) (int64, *framework.Status) {
	klog.V(6).InfoS("Calculating score", "pod", klog.KObj(pod), "nodeName", nodeName)
	score := framework.MinNodeScore
	nodeInfo, err := pl.handle.SnapshotSharedLister().NodeInfos().Get(nodeName)
	if err != nil {
		return score, framework.NewStatus(framework.Error, fmt.Sprintf("getting node %q from Snapshot: %v", nodeName, err))
	}
	// get node metrics
	metrics, _ := pl.collector.GetNodeMetrics(nodeName)
	if metrics == nil {
		klog.InfoS("Failed to get metrics for node; using minimum score", "nodeName", nodeName)
		return score, nil
	}
	podRequest := trimaran.GetResourceRequested(pod)
	node := nodeInfo.Node()

	// calculate CPU score
	var cpuScore float64 = 0
	cpuStats, cpuOK := trimaran.CreateResourceStats(metrics, node, podRequest, v1.ResourceCPU, watcher.CPU)
	if cpuOK {
		cpuScore = computeScore(cpuStats, pl.args.SafeVarianceMargin, pl.args.SafeVarianceSensitivity)
	}
	klog.V(6).InfoS("Calculating CPUScore", "pod", klog.KObj(pod), "nodeName", nodeName, "cpuScore", cpuScore)
	// calculate Memory score
	var memoryScore float64 = 0
	memoryStats, memoryOK := trimaran.CreateResourceStats(metrics, node, podRequest, v1.ResourceMemory, watcher.Memory)
	if memoryOK {
		memoryScore = computeScore(memoryStats, pl.args.SafeVarianceMargin, pl.args.SafeVarianceSensitivity)
	}
	klog.V(6).InfoS("Calculating MemoryScore", "pod", klog.KObj(pod), "nodeName", nodeName, "memoryScore", memoryScore)
	// calculate total score
	var totalScore float64 = 0
	if memoryOK && cpuOK {
		totalScore = math.Min(memoryScore, cpuScore)
	} else {
		totalScore = math.Max(memoryScore, cpuScore)
	}
	score = int64(math.Round(totalScore))
	klog.V(6).InfoS("Calculating totalScore", "pod", klog.KObj(pod), "nodeName", nodeName, "totalScore", score)
	return score, framework.NewStatus(framework.Success, "")
}
```

说明：

1. MinNodeScore 是 schedule-framework 定义的得分下边界，得分是一个 [0, 100] 范围内的值 [^8]

```
const (
	// MaxNodeScore is the maximum score a Score plugin is expected to return.
	MaxNodeScore int64 = 100

	// MinNodeScore is the minimum score a Score plugin is expected to return.
	MinNodeScore int64 = 0

	// MaxTotalScore is the maximum total score.
	MaxTotalScore int64 = math.MaxInt64
)
```

2. 获取所有 node 的统计指标数组，从 apiserver watch的结果中获取，每个元素的结构是 Metric 数组，每个 Metric 代表 cpu、mem等一类资源：

> pkg/watcher/watcher.go [^9]

```
type Metric struct {
	Name     string  `json:"name"`             // Name of metric at the provider
	Type     string  `json:"type"`             // CPU or Memory
	Operator string  `json:"operator"`         // STD or AVE or SUM, etc.
	Rollup   string  `json:"rollup,omitempty"` // Rollup used for metric calculation
	Value    float64 `json:"value"`            // Value is expected to be in %
}
```

3. 获取 pod 的资源请求量
4. 依次计算 cpu、mem 的得分，如果node 的统计指标存在，计算之

> pkg/trimaran/loadvariationriskbalancing/analysis.go [^10]

```
/*
Calculation of risk score for resources given measured data
*/

// computeScore : compute score given usage statistics
// - risk = [ average + margin * stDev^{1/sensitivity} ] / 2
// - score = ( 1 - risk ) * maxScore
func computeScore(rs *trimaran.ResourceStats, margin float64, sensitivity float64) float64 {
	if rs.Capacity <= 0 {
		klog.ErrorS(nil, "Invalid resource capacity", "capacity", rs.Capacity)
		return 0
	}

	// make sure values are within bounds
	rs.Req = math.Max(rs.Req, 0)
	rs.UsedAvg = math.Max(math.Min(rs.UsedAvg, rs.Capacity), 0)
	rs.UsedStdev = math.Max(math.Min(rs.UsedStdev, rs.Capacity), 0)

	// calculate average and deviation factors
	mu, sigma := trimaran.GetMuSigma(rs)

	// apply root power
	if sensitivity >= 0 {
		sigma = math.Pow(sigma, 1/sensitivity)
	}
	// apply multiplier
	sigma *= margin
	sigma = math.Max(math.Min(sigma, 1), 0)

	// evaluate overall risk factor
	risk := (mu + sigma) / 2
	klog.V(6).InfoS("Evaluating risk factor", "mu", mu, "sigma", sigma, "margin", margin, "sensitivity", sensitivity, "risk", risk)
	return (1. - risk) * float64(framework.MaxNodeScore)
}
```

具体打分逻辑：

1. 首先检查资源容量，并确保资源合法
2. 计算平均值和标准差（有存储历史数据值，历史样本存储大小可以设置）
3. 调整标准差：
    - 如果 sensitivity 是正数，就对标准差进行调整。（敏感度调整了计算过程中对波动（即标准差）的重视程度，当 sensitivity > 1 时，标准差的值会减少（因为标准差的指数变小）；当 sensitivity < 1 时，标准差的值会增加（因为标准差的指数变大））
    - 然后乘以 margin（边际系数），这个值用来增加或减少风险，通过对标准差（sigma）进行乘法操作，直接影响风险因子的大小
    - 最后确保标准差在 [0, 1] 范围内
4. 计算风险因子 risk，它是平均值和调整后的标准差的平均值，这个风险因子反映了节点资源使用的整体情况
5. 计算最终得分 `(1-risk) * maxScore`，如果risk 高，意味着资源使用情况不稳定，得分会低，反之亦然

最后
5. 如果 cpu 和 mem 状态都ok，取最小值（短板效应）；如果有不OK的，取最大值，因为不OK的得分是0

# schedule-framework

在 Kubernetes 1.18 及之后的版本，调度器框架引入了插件机制，可以更灵活地定制调度行为。定制可以分为三种：

1. 定制过滤和打分过程中的各个 Plugin
2. 修改Plugin的执行顺序
3. 定制整个调度器，替换原调度器，或者多调度器

## 定制 Plugin

围绕 Filter、Score 有一些钩子阶段：PreFilter、PostFilter、PreScore、NormalizeScore

**假如我们把资源评估步骤以plugin的形式提供，该如何做呢？**

1. 实现 FilterPlugin 接口，想在哪个阶段被调用，就实现相应阶段的接口，例如 PostFilterPlugin、PreScorePlugin 等

> pkg/scheduler/framework/interface.go [^1]

```
type FilterPlugin interface {
	Filter(ctx context.Context, state *CycleState, pod *v1.Pod, nodeInfo *NodeInfo) *Status
}
```

7. 注册插件

```
import (
    "k8s.io/kubernetes/pkg/scheduler/framework/runtime"
    "k8s.io/kubernetes/pkg/scheduler/framework/runtime/registry"
)

func registerPlugins(registry *registry.Registry) {
    registry.Register("MyFilterPlugin", func(_ runtime.Object, _ framework.Handle) (framework.Plugin, error) {
        return &MyFilterPlugin{}, nil
    })
    registry.Register("MyScorePlugin", func(_ runtime.Object, _ framework.Handle) (framework.Plugin, error) {
        return &MyScorePlugin{}, nil
    })
}
```

9. 部署插件

例如以 deployment 来部署

10. 配置调度器使用插件

```
apiVersion: kubescheduler.config.k8s.io/v1beta2
kind: KubeSchedulerConfiguration
profiles:
  - schedulerName: default-scheduler
    plugins:
      filter:
        enabled:
          - name: MyFilterPlugin
      score:
        enabled:
          - name: MyScorePlugin
```

11. 测试

在 kind 集群中测试示例插件。

## 修改Plugin的执行顺序

通过 `KubeSchedulerConfiguration`可以修改调度器的行为，例如调整 filter 节点的插件顺序：

```
apiVersion: kubescheduler.config.k8s.io/v1beta2
kind: KubeSchedulerConfiguration
profiles:
  - schedulerName: default-scheduler
    plugins:
      preFilter:
        enabled:
          - name: DefaultPreFilterPlugin
        disabled:
          - name: "*"
      filter:
        enabled:
          - name: NodeAfinity
          - name: NodeResourcesFit
        disabled:
          - name: "*"
      postFilter:
        enabled:
          - name: DefaultPostFilterPlugin
        disabled:
          - name: "*"
```

profiles[i].plugins["filter"].enabled 指定了启用的插件，以及执行的顺序。

因为各个 Plugin 是顺序执行的，例如如果调度器配置资源过滤器先于亲和性过滤器，那么被资源过滤器滤掉的Node不会输入亲和性过滤器。调整顺序的这个能力在某些场景会极大提高调度效率：例如在一个大集群中，有一批集群是有GPU的机器，当调度GPU应用时，先通过 Label 或亲和性过滤GPU机器，再过资源过滤器，就会提高调度效率。

## 定制整个调度器，替换原调度器，或者多调度器

使用多调度器需要做的工作：

1. 部署自定义调度器：创建一个新的调度器，使用不同的调度策略
2. 配置Pod使用特定的调度器：在Pod配置中指定使用哪个调度器
3. 修改 kube-scheduler 配置：确保默认调度器和自定义调度器可以并存运行

### 部署自定义调度器

1. 编写`KubeSchedulerConfiguration`，
2. 调度器 Pod 使用该配置

```
apiVersion: v1
kind: Pod
metadata:
  name: custom-scheduler
  namespace: kube-system
  labels:
    component: custom-scheduler
spec:
  containers:
    - name: custom-scheduler
      image: k8s.gcr.io/kube-scheduler:v1.21.0
      command:
        - /usr/local/bin/kube-scheduler
        - --config=/etc/kubernetes/scheduler-config.yaml
      volumeMounts:
        - name: config-volume
          mountPath: /etc/kubernetes/scheduler-config.yaml
          subPath: scheduler-config.yaml
  volumes:
    - name: config-volume
      configMap:
        name: custom-scheduler-config
```

### 配置Pod使用特定的调度器

在Pod的配置中，通过 spec.schedulerName 字段指定调度器名称。例如，使用上述的 custom-scheduler 调度器：

```
apiVersion: v1
kind: Pod
metadata:
  name: custom-scheduler-pod
spec:
  schedulerName: custom-scheduler
  containers:
    - name: nginx
      image: nginx
```

### 修改 kube-scheduler 配置

确保默认调度器和自定义调度器可以并存运行。默认调度器通常已经在集群中运行，只需要确保它不会与自定义调度器发生冲突。例如：

- 调度器名称要唯一，
- Pod 的 spec.schedulerName 字段明确指定，确保调度器只处理分配给它的Pod

# 批量调度（Batch Scheduling）

批量调度是指在 Kubernetes 中调度一组 Pod，而不是单个 Pod。这种调度方式在需要同时调度多个互相关联的 Pod 时非常有用，比如在大数据处理、机器学习训练等场景中。实现批量调度的方法有：

1. 使用 Kubernetes 自带能力：如 Job/CronJob，适用于简单的一次性或定时批处理任务
2. 通过扩展 Kubernetes：使用调度器插件（Schedule Framework），或者使用社区的方案（Volcano）
3. 使用工作流（Argo Workflow），适用于复杂的工作流和批处理任务，支持多步骤和依赖关系

[^1]: https://github.com/kubernetes/kubernetes/blob/8cf93c8d83df3a206ab4abe2ed2ead7a173bd63e/pkg/scheduler/framework/interface.go#L426
[^2]: https://kubernetes.io/zh-cn/docs/concepts/scheduling-eviction/scheduling-framework/
[^3]: https://github.com/kubernetes/community/blob/f03b6d5692bd979f07dd472e7b6836b2dad0fd9b/contributors/devel/sig-scheduling/scheduler_queues.md
[^4]: https://github.com/kubernetes/kubernetes/blob/93d56511e684369479f23aae15617e483cda5719/pkg/scheduler/scheduler.go#L65
[^5]: https://github.com/kubernetes/kubernetes/blob/db9419c01dabe5f803a900c2c2213ac1aaf39b04/pkg/scheduler/scheduler.go#L366
[^6]: https://github.com/kubernetes/kubernetes/blob/db9419c01dabe5f803a900c2c2213ac1aaf39b04/pkg/scheduler/internal/queue/scheduling_queue.go#L152
[^7]: https://github.com/kubernetes-sigs/scheduler-plugins/blob/7c477adb5e1f4fffe5a7913c871575e686e0542e/pkg/trimaran/loadvariationriskbalancing/loadvariationriskbalancing.go#L81
[^8]: https://github.com/kubernetes/kubernetes/blob/7ec344dcef9a04920578aabe4e122bc0b3404afe/pkg/scheduler/framework/interface.go#L147
[^9]: https://github.com/paypal/load-watcher/blob/c374a7c70913cfce6301a69db0208e288c2149c3/pkg/watcher/watcher.go#L71C1-L77C2
[^10]: https://github.com/kubernetes-sigs/scheduler-plugins/blob/7c477adb5e1f4fffe5a7913c871575e686e0542e/pkg/trimaran/loadvariationriskbalancing/analysis.go#L34
