### ISSUE TITLE
Kubernetes 大规模集群设计

### ISSUE THREAD

**Issue by QingyaFan** [QingyaFan/blog#60]
apiserver 是 k8s 集群的控制面，当集群规模变大，apiserver 会有很大压力。

# apiserver

## 接入层：限流

**使用 Admission Webhook[^1] 实现限流**

限流的实现机制：

Admission Webhook 分为 ValidatingAdmissionWebhook 和 MutatingAdmissionWebhook，我们可以编写一个 AdmissionWebhook 服务，例如名叫 `requests-limiter`，注册为 ValidatingAdmissionWebhook：

```
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "requests-limiter"
webhooks:
- name: "requests-limiter"
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    operations: ["CREATE"]
    resources: ["pods"]
    scope: "Namespaced"
  clientConfig:
    service:
      name: "requests-limiter"
      namespace: "requests-limiter"
    caBundle: <CA_BUNDLE>
  admissionReviewVersions: ["v1"]
  sideEffects: Unknown
  timeoutSeconds: 5
```

`requests-limiter` 实现的限流策略：

1. 请求拦截：拒绝非业务 IP 段内请求
2. 并发控制

## 缓存层：调整 watchCache 大小

watchCache 在 apiserver 请求之前加了一道缓存，主要缓存客户端 watch 的资源对象，如果 size 太小会导致 `too old resource version`，进而重新 list apiserver，所以在资源允许情况下，根据集群规模设置大小会降低 apiserver 的压力。参数是： `--watch-cache-size`

## 实现层

具体 apiserver 代码有哪些性能差的实现，我们可以通过 pprof 进行分析，针对性优化，然后回馈社区~

# Etcd

etcd 也曾在重构过程中出现过数据不一致问题[^2]，已知有几个厂踩过这个坑。

## hdd => ssd

> Fast disks are the most critical factor for etcd deployment performance and stability. [^3]

Etcd 性能和稳定的关键是磁盘，这是因为 etcd 的共识协议依赖持久化日志，如果写操作耗时过长，心跳可能会超时并触发选举，影响集群稳定性。Etcd 对磁盘写入延迟非常敏感，通常需要至少 50 Sequencial IOPS（hdd 水平），如果集群负载较大，建议至少 500 Sequencial IOPS（典型 ssd 水平）；对于磁盘的带宽根据业务数据量配置即可，主要考虑故障恢复能容忍的时间：例如你有 1G的数据，需要故障后在 15s内恢复，则需要至少 100MB/s 的磁盘带宽。

todo：raft 选举过程是什么样的，为什么需要磁盘性能高？

# 调度

## 调度吞吐
调度慢问题：单集群调度吞吐x万Pod/秒

## 混布调度

在线服务和离线服务不能部署在一起，避免离线服务影响在线服务，在线服务的QoS应该比离线高。

# 网络

iptables => IPVS

# 绕过去

用集群联邦（Federation）可以解决上述单个大集群遇到的性能瓶颈和优化工作，且有更高的可用性，但可能控制面会稍微复杂。

选择集群联邦还是单个大集群，取决于具体的需求和使用场景。如果需要跨地域部署、容灾和高可用性，集群联邦可能更适合；如果资源集中管理、低延迟和简化运维是主要需求，单个大集群可能更适合。两者各有优劣，需要根据具体情况权衡和选择。

todo

[^1]: https://kubernetes.io/zh-cn/docs/reference/access-authn-authz/extensible-admission-controllers/
[^2]: https://github.com/etcd-io/etcd/blob/main/Documentation/postmortems/v3.5-data-inconsistency.md
[^3]: https://etcd.io/docs/v3.6/op-guide/hardware/
