### ISSUE TITLE
PaaS技术：基于OAM的Kubevela

### ISSUE THREAD

**Issue by QingyaFan** [QingyaFan/blog#76]
Kubevela 是什么，和OAM是什么关系，架构和实现是怎么样的？

KubeVela的github项目介绍是“The Modern Application Platform”，突出了是一个应用平台，旨在简化和优化云原生应用程序的交付和管理，主要是 PaaS中的 CD 环节。专注于以下几个方面：

1. 现代化的应用交付

    - 声明式配置：KubeVela 提供了基于 Open Application Model（OAM）的声明式方式，开发者可以通过简洁的配置文件描述应用程序的部署需求和策略，而不需要了解底层 Kubernetes 资源的复杂性
    - 可扩展性：KubeVela 可以根据不同的业务需求和技术栈进行扩展，支持多种部署策略（如蓝绿部署、金丝雀发布）和不同的云环境（多云、混合云）

2. 面向应用的管理

    - 应用声明周期管理：KubeVela 提供了从开发到生产环境的完整生命周期管理中的部分环节，包括部署、扩展、升级、回滚等操作
    - 多环境支持：KubeVela 支持跨多个环境（如开发、测试、生产）的一致性应用交付，帮助团队更好地管理和维护复杂的云原生应用

3. 平台化能力：简化开发者体验，统一的应用模型
4. 与 CI/CD 工具集成：
    - 自动化工作流：KubeVela 本身并不专注于 CI/CD，但它可以与 CI/CD 工具集成，从而构建自动化的应用交付流水线；
    - 应用级别的管理：通过与 CI/CD 工具的结合，KubeVela 可以在代码交付之后，负责应用在 Kubernetes 上的具体部署和管理操作。

# OAM

[OAM](https://oam.dev/) 是 Open Application Model的缩写，是一个用于定义和管理云原生应用的开放标准，微软和阿里联合提出，旨在解决多种云环境中部署和管理的复杂性。

OAM规范的核心概念包括：

1. Component（组件）：应用的最小单元，描述了应用的可执行部分，比如一个容器或一组容器。组件定义了应用程序的核心逻辑
2. Trait（特性）：用于扩展组件的行为，类似于为组件添加功能或配置，比如自动扩展、日志配置能力等
3. Scope（作用域）：用于定义组件之间的关系或应用的一些运行时约束，比如网络隔离、部署区域等
4. Application Configuration（应用配置）：将组件、特性和作用域组合在一起，形成完整的应用描述，便于在不同环境中进行部署

OAM 最初的实现是 Rust 实现的 [Rudr](https://github.com/oam-dev/rudr)，后来 Golang 实现的 [KubeVela](https://github.com/kubevela/kubevela) 代替。

## OAM描述应用的例子 

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app
spec:
  components:
    - name: express-server
      type: webservice
      properties:
        image: oamdev/hello-world
        ports:
          - port: 8000
            expose: true
      traits:
        - type: scaler
          properties:
            replicas: 1
  policies:
    - name: target-default
      type: topology
      properties:
        clusters: ["local"]
        namespace: "default"
    - name: target-prod
      type: topology
      properties:
        clusters: ["local"]
        namespace: "prod"
    - name: deploy-ha
      type: override
      properties:
        components:
          - type: webservice
            traits:
              - type: scaler
                properties:
                  replicas: 2
  workflow:
    steps:
      - name: deploy2default
        type: deploy
        properties:
          policies: ["target-default"]
      - name: manual-approval
        type: suspend
      - name: deploy2prod
        type: deploy
        properties:
          policies: ["target-prod", "deploy-ha"]
```

完整的Application定义可以参考[这里](https://github.com/kubevela/kubevela/blob/3f87c6f2e711db85a2c3af1648a5e4e9c1bce6ab/apis/core.oam.dev/v1beta1/application_types.go#L81)。OAM 中的 Application 对象基本包含 components、policies、workflow 三部分：

- components：描述应用主体
- policies：Policies defines the global policies for all components in the app, e.g. security, metrics, gitops, multi-cluster placement rules, etc. Policies are applied after components are rendered and before workflow steps are executed.
- workflow：Workflow defines how to customize the control logic. And workflow steps are executed in array order.

todo: 重要的字段定义

# Kubevela

todo：kubevela对OAM的具体实现
