### ISSUE TITLE
Kubernetes的包管理器：Helm

### ISSUE THREAD

**Issue by QingyaFan** [QingyaFan/blog#81]
# Helm 用法

Helm 是 Kubernetes 包管理工具，支持应用的定义、安装和管理。

Helm管理工具有几个重要概念：
- chart，应用的YAML描述和配置，类似于软件包，包括Kubernetes集群中的资源定义。
- repo，是 chart的仓库，存储和维护多个chart。Helm可以管理repo，在添加的repo中搜索和安装chart。
- release，release是chart在Kubernetes集群中部署的一个实例，一个chart可以部署多个release，每个release有不同的配置

## 常用 Helm 命令

在找文档之前，不妨先看看 `helm --help` 和 `man helm`，内容很丰富，很多时候可以直接解决！

### 1. 仓库管理

helm 主要是管理 chart，并允许chart分布在不同的repo中，我们想对repo做管理，要用 `repo` 子命令。

- 添加 Chart 仓库 `helm repo add <repo-name> <repo-url>`。例如：`helm repo add stable https://charts.helm.sh/stable`
- 更新Helm仓库 `helm repo update`
- 列出添加的仓库 `helm repo list`

### 2. Chart管理

> Helm包涵盖了将Kubernetes资源安装到Kubernetes集群所需要的足够多的信息。Charts包含Chart.yaml文件和模板，默认值(values.yaml)，以及相关依赖。Charts开发设计了良好定义的目录结构，并且打包成了一种称为 chart archive 文件格式。

- 搜索 Chart `helm search repo <chart-name>`
- 安装 Chart `helm install <release-name> <chart-name>`

示例：

```bash
helm install my-mysql stable/mysql
```

- 使用自定义的 values 文件安装：`helm install <release-name> <chart-name> -f <value-file>
- 查看 Chart 的详细信息 `helm show chart <chart-name>`
- 查看 Chart 的 values 文件 `helm show values <chart-name>`
- 打包 Chart `helm package <chart-directory`>
- 上传 Chart 到仓库 `helm push <chart-name> <repo-name>

### 3. 管理 Release

> chart安装之后，Helm库会创建一个 release 来跟踪这个安装。单个chart可以在同一个集群中安装多次，并能创建多个不同的版本。例如，可以使用 helm install 命令以不同的版本安装三个PostgreSQL 数据库三次。

- 列出所有 Release：`helm list`
- 查看特定 Release 的状态：`helm status <release-name>`
- 卸载 Release：`helm uninstall <release-name>`
- 升级 Release：`helm upgrade <release-name> <chart-name>`

### 4. 其他

- 验证 Chart `helm lint <chart-directory>`
- 模板渲染 `helm template <chart-name>`

ref: https://helm.sh/docs/helm/helm/

# Helm Chart 结构和语法

## Chart 语法和结构

一个 Helm Chart 是一个打包的 Kubernetes 应用程序，包含了 Kubernetes 资源的定义文件以及描述如何安装和配置该应用程序的元数据。典型的 Helm Chart 目录结构和内容如下：

```
my-chart/
  ├── Chart.yaml
  ├── values.yaml
  ├── templates/
  ├── charts/
  └── .helmignore
```

**主要文件和目录**

1. `Chart.yaml`: Chart的元数据文件，包含有关该chart的基本信息，如名称、版本、描述等

内容示例：

```
apiVersion: v2 # helm API版本，v2是helm3的版本
name: my-chart # chart名称
description: A Helm Chart for Kubernetes
version: 0.1.0 # chart version
appVersion: 1.0.0 # app version
```

2. `values.yaml`: 默认的配置文件，定义 Chart 中的变量的默认值。用户可以通过修改该文件或使用 `--set` 参数来覆盖这些值（helm install -h 的帮助文档中说明了使用 --set 传递要覆盖的value），从而定制 Chart 的部署

内容示例：

```
replicaCount: 2
image:
  repository: nginx
  tag: "1.16"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
```

3. `templates/`: 这个目录存放Kubernetes资源的模板文件。模板文件使用Helm的Go模版引擎，可以根据 `values.yaml` 中的变量生成具体的 Kubernetes 资源文件。

常见模板文件：

- deployment.yaml: 定义应用的 Deployment 资源
- service.yaml: 定义应用的 Service 资源
- ingress.yaml: 定义 Ingress 资源（如果有）
- configmap.yaml: 定义 ConfigMap 资源

模板示例：

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
```

模版中常见的占位符：

- {{ .Values.xxx }}: 引用 values.yaml 中定义的变量
- {{ .Release.Name }}: 引用 Helm Release的名称
- {{ .Chart.Name }}: 引用 Chart 的名字
- {{ .Release.Namespace }}: 引用安装 Chart 的 Kubernetes 命名空间

4. `charts/`: 存放该 Chart 的依赖 Charts。如果某个 Chart 依赖于其它的 Charts（比如数据库、消息队列等），这些依赖可以放在 `charts/` 目录，或者通过 `Chart.yaml` 中定义的依赖项自动下载。 

示例（Chart.yaml中定义依赖）：

```
apiVersion: v2 # helm API版本，v2是helm3的版本
name: my-chart # chart名称
description: A Helm Chart for Kubernetes
version: 0.1.0 # chart version
appVersion: 1.0.0 # app version
dependencies:
  - name: mariadb
    version: 7.x.x
    repository: "https://charts.bitnami.com/bitnami"
```

5. `.helmignore`: 类似于 .gitignore，用于指定在打包 Chart 时应忽略的文件。通常用于排除不需要的文件或目录，已减小 Chart 的体积。

示例：

```
.idea
.DS_Store
tests/
```

**其他可选的文件**

1. NOTES.txt: 在 Helm 安装或升级 Chart 时显示的提示信息或指引。通常用于给用户提供一些操作建议或下一步指引

示例：

```
Your application is deployed!
You can run `kubectl get pods` to check the status.
```

2. README.md: 可选的文档文件，用于描述 Chart 的功能、安装方法和使用说明。它可以帮助用户快速了解如何使用这个 Chart
3. requirements.yaml（Helm 2）：在Helm2中用于定义 Chart 的依赖项。Helm 3 中已经将依赖定义移动到 Chart.yaml 中

### chart 的 hook

在安装chart的生命周期中的某个阶段执行一些动作，例如安装crd。在helm v2中，只需在templates/xxx.yaml中对象的metadata.annotation 添加相应kv。例如一些对象的创建需要事先安装crd：

```
apiVersion: v1
kind: xxx
metadata:
  annotations:
    "helm.sh/hook": "crd-install"
# ....
```

## Chart Hub

ArtifactHub：https://artifacthub.io/

# Helm vs Kustomize

Helm 和 Kustomize 是 Kubernetes 中常用的两种配置管理工具，它们都有助于管理 Kubernetes 资源，但各自采用不同的方式和理念。以下是两者的主要区别：

1. 基础理念

- Helm：Helm 是一种模板化的 Kubernetes 包管理工具。它通过Chart（打包的Kubernetes应用）将应用的部署文件打包，可以使用参数化的模板来生成 Kubernetes 资源文件。
    - Helm 提供了一个高度灵活的方式来部署应用程序，允许用户通过 Helm 的模板语法定义参数化的 YAML 文件，并且可以打包和复用这些模板。_**todo**_：Helm的模板语法都有哪些，有何特别之处

- Kustomize：Kustomize 是一种通过覆盖（overlay）和patch来管理 Kubernetes 资源的工具，它不使用模板。相反，Kustomize 使用 YAML 的原生功能，对现有的 Kubernetes 资源文件进行修改和组合。
    - Kustomize 更加注重直接修改现有的 YAML 文件，并提供不同环境下资源的差异化管理（比如开发、生产等）。它的特点是“原生 Kubernetes 支持”，不需要引入额外的模板语法。_**todo**_：来一个kustomize的例子

9. 模板化 vs 原生 YAML

- 通过模板系统动态生成 YAML 文件。Helm 的模板功能允许在模板中使用变量和逻辑，因此可以根据输入的值生成不同的配置。例如，可以为不同的环境使用不同的参数来生成不同的配置文件。
- Kustomize：没有模板系统，它操作的是原生的 Kubernetes YAML 文件。它通过叠加和修改（patch）来组合资源文件，这使得 YAML 文件本身更加可读和可维护。例如，Kustomize 可以定义一个基础的资源文件，然后针对不同的环境（如开发和生产）应用不同的 patch 来修改这些基础文件。

10. 封装 vs 组合

- Helm：封装成 Chart，作为打包好的应用发布和复用，类似应用商店的方式。你可以从 Helm 仓库中下载预定义的 Chart 并安装它们。Helm Chart 可以定义依赖，并且支持版本管理，非常适合复杂的、多服务的应用部署。todo：还有chart如何管理适用的k8s版本？
- Kustomize：通过组合已有的 YAML 资源文件进行管理。你可以使用 Kustomize 的 base 和 overlay 机制，针对不同的部署场景（如开发、测试、生产环境）叠加不同的配置。

11. 社区集成

- Helm：Helm 已经被大量项目采用，并有丰富的官方和社区 Chart 仓库支持。它还集成了升级、回滚等功能，可以管理应用的生命周期。
- Kustomize：Kustomize 从 Kubernetes 1.14 开始成为 kubectl 命令行工具的一部分，因此无需额外安装，可以通过 kubectl apply -k 直接应用 Kustomize 配置。这使得它在 Kubernetes 原生环境下的集成非常好。todo：使用方法？

12. 管理应用的方式

- Helm：管理应用的方式更加复杂，适合需要多个参数化和定制化需求的场景，可以处理依赖关系。todo：如何处理依赖系统？
- Kustomize：更偏向于简单的修改和组合资源，适合 YAML 资源管理和多环境差异化配置，简单易用。

13. 依赖管理

- Helm：Helm 支持定义和管理依赖（通过 requirements.yaml 或 Chart.yaml），可以安装依赖的子 Chart。
- Kustomize：Kustomize 没有依赖管理的概念。它依赖的是通过 bases 组合多个已有的资源文件，没有类似 Helm 的依赖管理功能。

**什么时候使用 Helm vs Kustomize？**

- Helm 更适合复杂的应用程序或需要重度参数化的场景，尤其是需要管理不同版本或依赖的情况下。
- Kustomize 更适合注重原生 Kubernetes 体验和简单配置管理的场景，特别是当你需要管理不同环境之间的差异时。

总结

- Helm 通过模板系统和封装机制提供了灵活的参数化管理，并适合复杂应用的生命周期管理。
- Kustomize 则通过原生的 YAML 组合和覆盖提供了简单而直接的 Kubernetes 资源管理方式。
