### ISSUE TITLE
详解YAML

### ISSUE THREAD

**Issue by QingyaFan** [QingyaFan/blog#86]
YAML 语法主要基于缩进和简单的标记。

### 基础结构

1. 键值对 `key: value`
2. 缩进：缩进用来表示层级关系。使用空格进行缩进，通常使用两个空格（不可使用制表符）
3. 序列（List）：使用 `-` 前缀表示列表项

```
fruits:
  - apple
  - banana
  - cherry
```

4. 映射（Dictionary）：嵌套键值对

```
person:
  name: Alice
  age: 30
  address:
    street: 123 Main St
    city: Anytown
```

### 数据类型

1. 字符串：可以用单引号或双引号，包括不带引号的字符串（如果没有特殊字符串）。例如 `greeting: "Hello, World!"
2. 数字： `number: 42`
3. 布尔值： `is_active: true`，true/false均为小写字母
4. 空值：`some_key: null`
5. 注释：使用 `#` 开头的行是注释

```
# 这是注释
key: value  # 行内注释
```

6. 多行字符串：用 `|` 表示保留换行的多行字符串

```
description: |
  This is a multi-line string
  that retains line breaks.
```

用 `>` 表示折叠成单行的多行字符串：

```
summary: >
  This is a long string
  that will be folded
  into a single line.
```

7. 特殊字符

- 使用 " 和 ' 来定义字符串
- 使用 : 来定义键值对
- 使用 - 列出列表项
